# Generated by Django 5.0.6 on 2024-06-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_responsible_person_client_responsible_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='responsible_id',
            new_name='responsible',
        ),
    ]
