# Generated by Django 5.0.6 on 2024-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_responsible_id_client_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
